<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="meteo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="mesure" minOccurs="1" maxOccurs="unbounded" type="T_mesure"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="T_mesure">
            <xsd:sequence>
                <xsd:element name="ville" maxOccurs="unbounded" minOccurs="1" type="T_VILLE"/>
            </xsd:sequence>
            <xsd:attribute name="date" type="xsd:date" use="required" />
        </xsd:complexType>
    <xsd:complexType name="T_VILLE" >
            <xsd:attribute name="nom" type="xsd:string" use="required"/>
            <xsd:attribute name="temperature" type="xsd:int" use="required" />
        </xsd:complexType>
</xsd:schema>